language: node_js
node_js:
  - '8'
  - '11'

sudo: false

after_success:
  - npm run coverage
  - npm run build

deploy:
  skip_cleanup: true
  provider: npm
  email: "hugo.armstrong@gmail.com"
  api_key: $api_key
  on:
    tags: true
